import { useState, type FormEvent } from 'react';
import { Activity, ArrowLeft, BookOpen, CalendarDays, Check, ClipboardList, FileText, LayoutDashboard, LogOut, Menu, Plus, Send, ShieldCheck, Store } from 'lucide-react';
import { useApp } from '@/i18n/AppContext';

type View = 'dashboard' | 'events' | 'content' | 'audit';
type Status = 'pending' | 'approved' | 'published' | 'needs-info' | 'rejected';
type Proposal = { id: number; date: string; title: string; organizer: string; schedule: string; location: string; equipment: string; status: Status; conflict?: string };
const initial: Proposal[] = [
  { id: 1, date: '2026-09-20', title: 'Workshop vẽ minh họa sách tranh', organizer: 'Nhà xuất bản Mầm Non', schedule: '20/09/2026 · 14:00–16:30', location: 'Khu trưng bày – giao lưu tác giả', equipment: 'Âm thanh, 4 bàn, 40 ghế', status: 'pending', conflict: 'Trùng không gian và khung giờ với sự kiện “Gặp gỡ tác giả trẻ”.' },
  { id: 2, date: '2026-09-25', title: 'Ngày hội đổi sách xanh', organizer: 'CLB Sống xanh', schedule: '25/09/2026 · 08:30–11:30', location: 'Sân khấu chính', equipment: 'Âm thanh, 30 ghế', status: 'pending' },
  { id: 3, date: '2026-09-27', title: 'Tọa đàm văn học thiếu nhi', organizer: 'NXB Trẻ', schedule: '27/09/2026 · 09:00–11:00', location: 'Sân khấu chính', equipment: 'Âm thanh, máy chiếu', status: 'approved' },
];
const label: Record<Status, string> = { pending: 'Chờ duyệt', approved: 'Đã duyệt', published: 'Đã công bố', 'needs-info': 'Cần bổ sung', rejected: 'Từ chối' };
const color: Record<Status, string> = { pending: 'bg-amber-100 text-amber-800', approved: 'bg-blue-100 text-blue-800', published: 'bg-emerald-100 text-emerald-800', 'needs-info': 'bg-orange-100 text-orange-800', rejected: 'bg-red-100 text-red-800' };

export function AdminPortal() {
  const { navigate } = useApp(); const [auth, setAuth] = useState(false); const [view, setView] = useState<View>('dashboard'); const [menu, setMenu] = useState(false); const [proposals, setProposals] = useState(initial); const [logs, setLogs] = useState(['09:12 · Nguyễn Minh An đăng nhập hệ thống.', '08:45 · Lê Thu Hà cập nhật gian hàng A03.', 'Hôm qua · Trần Quốc Bảo công bố “Hội sách cuối tuần”.']); const [items, setItems] = useState(['Gian hàng A01 — NXB Trẻ', 'Gian hàng A02 — Đông Tây Book', 'Bài viết: Cẩm nang tham quan Đường Sách']);
  const now = new Date();
  const currentMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const monthProposals = proposals.filter((item) => item.date.startsWith(currentMonth));
  const pending = monthProposals.filter(x => x.status === 'pending' || x.status === 'needs-info').length;
  const approved = monthProposals.filter(x => x.status === 'approved' || x.status === 'published').length;
  const conflicts = monthProposals.filter(x => Boolean(x.conflict) && (x.status === 'pending' || x.status === 'needs-info')).length;
  const log = (s: string) => setLogs(x => [`Vừa xong · ${s}`, ...x]);
  const change = (id: number, status: Status, action: string) => { const found = proposals.find(x => x.id === id); setProposals(x => x.map(p => p.id === id ? {...p, status} : p)); if (found) log(`Nguyễn Minh An ${action} “${found.title}”.`); };
  if (!auth) return <Login back={() => navigate('home')} enter={() => {setAuth(true); log('Nguyễn Minh An đăng nhập hệ thống.');}} />;
  const nav = [{id:'dashboard' as View, text:'Tổng quan', Icon:LayoutDashboard}, {id:'events' as View,text:'Phê duyệt sự kiện',Icon:CalendarDays}, {id:'content' as View,text:'Quản lý nội dung',Icon:FileText}, {id:'audit' as View,text:'Nhật ký hoạt động',Icon:ClipboardList}];
  return <div className="min-h-screen bg-slate-50"><aside className={`fixed z-50 inset-y-0 left-0 w-72 bg-slate-950 text-slate-200 transition-transform lg:translate-x-0 ${menu?'translate-x-0':'-translate-x-full'}`}><div className="h-20 px-6 flex items-center gap-3 border-b border-white/10"><div className="p-2.5 rounded-xl bg-emerald-500"><BookOpen size={21}/></div><div><b className="text-white">ĐƯỜNG SÁCH</b><p className="text-xs text-slate-400">Cổng quản trị nội bộ</p></div></div><nav className="p-4 space-y-1">{nav.map(({id,text,Icon})=><button key={id} onClick={()=>{setView(id);setMenu(false)}} className={`w-full flex gap-3 items-center p-3 rounded-lg text-sm ${view===id?'bg-emerald-500 text-white':'hover:bg-white/10'}`}><Icon size={18}/>{text}{id==='events'&&pending>0?<span className="ml-auto bg-white/20 rounded-full px-2 text-xs">{pending}</span>:null}</button>)}</nav><button onClick={()=>navigate('home')} className="absolute bottom-4 left-4 right-4 flex gap-3 p-3 text-sm hover:bg-white/10 rounded-lg"><ArrowLeft size={18}/>Về website công khai</button></aside>{menu&&<button className="fixed inset-0 z-40 bg-slate-900/50 lg:hidden" onClick={()=>setMenu(false)}/>}<div className="lg:pl-72"><header className="h-20 bg-white border-b px-4 sm:px-7 flex justify-between items-center"><div className="flex gap-3 items-center"><button className="lg:hidden" onClick={()=>setMenu(true)}><Menu/></button><div><p className="text-xs text-slate-500">Quản trị nội bộ</p><h1 className="font-semibold">{nav.find(x=>x.id===view)?.text}</h1></div></div><div className="flex items-center gap-3"><div className="text-right hidden sm:block"><p className="text-sm font-medium">Nguyễn Minh An</p><p className="text-xs text-slate-500">Admin</p></div><span className="w-9 h-9 grid place-items-center rounded-full bg-emerald-100 text-emerald-700 font-bold">NA</span><button onClick={()=>setAuth(false)} className="text-slate-500"><LogOut size={19}/></button></div></header><main className="p-4 sm:p-7 max-w-[1600px] mx-auto">{view==='dashboard'&&<Dashboard pending={pending} approved={approved} conflicts={conflicts} schedule={monthProposals} events={()=>setView('events')}/>} {view==='events'&&<Review data={proposals} change={change}/>} {view==='content'&&<Content items={items} setItems={setItems} log={log}/>} {view==='audit'&&<Audit logs={logs}/>}</main></div></div>;
}
function Login({back,enter}:{back:()=>void;enter:()=>void}) { const submit=(e:FormEvent)=>{e.preventDefault();enter()}; return <div className="min-h-screen grid place-items-center bg-slate-950 p-4"><div className="max-w-md w-full bg-white rounded-2xl p-8 shadow-2xl"><button onClick={back} className="flex gap-1 text-sm text-slate-500 mb-8"><ArrowLeft size={16}/>Website công khai</button><div className="w-12 h-12 grid place-items-center bg-emerald-100 text-emerald-700 rounded-xl"><ShieldCheck/></div><h1 className="mt-4 text-2xl font-bold">Đăng nhập quản trị</h1><p className="mt-2 text-sm text-slate-500">Chỉ dành cho Ban quản lý và nhân sự Đường Sách.</p><form onSubmit={submit} className="space-y-4 mt-7"><input type="email" required defaultValue="admin@duongsach.tphcm.gov.vn" className="input-field" aria-label="Email nội bộ"/><input type="password" required defaultValue="password" className="input-field" aria-label="Mật khẩu"/><button className="w-full py-3 bg-emerald-600 text-white rounded-lg">Đăng nhập an toàn</button></form><p className="mt-5 text-xs text-slate-400">Giao diện mẫu; cần kết nối xác thực máy chủ và RBAC trước khi triển khai thực tế.</p></div></div> }
function Dashboard({ pending, approved, conflicts, schedule, events }: { pending: number; approved: number; conflicts: number; schedule: Proposal[]; events: () => void }) {
  const formatter = new Intl.DateTimeFormat('vi-VN', { month: 'long', year: 'numeric' });
  const monthName = formatter.format(new Date());
  const cards: Array<{ label: string; value: string; Icon: typeof Activity; tone: string }> = [
    { label: 'Đã duyệt trong tháng', value: String(approved), Icon: Check, tone: 'bg-emerald-50 text-emerald-600' },
    { label: 'Đang trùng lịch', value: String(conflicts), Icon: Activity, tone: 'bg-red-50 text-red-600' },
    { label: 'Chờ xét duyệt', value: String(pending), Icon: ClipboardList, tone: 'bg-amber-50 text-amber-600' },
  ];
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Xin chào, Nguyễn Minh An</h2><p className="text-slate-500 mt-1">Tổng quan lịch sự kiện {monthName}. Số liệu sẽ tự làm mới theo tháng.</p></div><div className="grid sm:grid-cols-3 gap-4">{cards.map(({ label, value, Icon, tone }) => <div key={label} className="bg-white border rounded-xl p-5"><span className={`w-10 h-10 grid place-items-center rounded-lg ${tone}`}><Icon size={20}/></span><p className="text-2xl font-bold mt-4">{value}</p><p className="text-sm text-slate-500">{label}</p></div>)}</div><section className="bg-white border rounded-xl p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-3 mb-6"><div><h3 className="font-semibold text-lg">Lịch sự kiện sắp tới</h3><p className="text-sm text-slate-500 mt-1">Thời gian biểu các hồ sơ trong {monthName}</p></div><button onClick={events} className="text-sm font-medium text-emerald-700">Xem hàng đợi →</button></div>{schedule.length === 0 ? <div className="py-12 text-center text-sm text-slate-500">Chưa có sự kiện nào trong tháng này.</div> : <div className="space-y-3">{schedule.sort((a, b) => a.date.localeCompare(b.date)).map((item) => <div key={item.id} className="grid grid-cols-[74px_1fr] sm:grid-cols-[120px_1fr_auto] gap-3 sm:gap-5 items-start border-l-2 border-emerald-400 pl-4 py-2"><div><p className="font-semibold text-sm">{item.schedule.split(' · ')[0]}</p><p className="text-xs text-slate-500 mt-1">{item.schedule.split(' · ')[1]}</p></div><div><p className="font-medium text-sm">{item.title}</p><p className="text-xs text-slate-500 mt-1">{item.location}</p>{item.conflict && (item.status === 'pending' || item.status === 'needs-info') ? <p className="text-xs text-red-600 mt-1">⚠ Có trùng lịch cần xử lý</p> : null}</div><span className={`w-fit px-2.5 py-1 rounded-full text-xs ${color[item.status]}`}>{label[item.status]}</span></div>)}</div>}</section></div>;
}
function Review({data,change}:{data:Proposal[];change:(id:number,s:Status,a:string)=>void}) { return <div><h2 className="text-2xl font-bold">Hàng đợi phê duyệt</h2><p className="text-slate-500 mt-1 mb-6">Kiểm tra lịch, không gian và thiết bị trước khi công bố.</p><div className="space-y-4">{data.map(x=><article key={x.id} className="bg-white border rounded-xl p-5"><div className="flex flex-col lg:flex-row justify-between gap-4"><div><div className="flex gap-2 flex-wrap items-center"><h3 className="text-lg font-semibold">{x.title}</h3><span className={`px-2.5 py-1 rounded-full text-xs ${color[x.status]}`}>{label[x.status]}</span></div><p className="text-sm text-slate-500 mt-1">Đề xuất bởi {x.organizer}</p><div className="grid sm:grid-cols-3 gap-3 mt-4 text-sm"><span><b>Thời gian:</b> {x.schedule}</span><span><b>Không gian:</b> {x.location}</span><span><b>Thiết bị:</b> {x.equipment}</span></div>{x.conflict&&x.status==='pending'?<p className="mt-4 bg-red-50 border border-red-200 text-red-800 rounded-lg p-3 text-sm"><b>Cảnh báo trùng lịch:</b> {x.conflict}</p>:null}</div>{x.status==='pending'?<div className="flex gap-2 flex-wrap h-fit"><button onClick={()=>change(x.id,'approved','đã duyệt')} className="px-3 py-2 text-sm rounded-lg bg-emerald-600 text-white"><Check size={14} className="inline"/> Duyệt</button><button onClick={()=>change(x.id,'needs-info','yêu cầu bổ sung')} className="px-3 py-2 text-sm rounded-lg border">Yêu cầu bổ sung</button><button onClick={()=>change(x.id,'rejected','từ chối')} className="px-3 py-2 text-sm rounded-lg border text-red-700">Từ chối</button></div>:x.status==='approved'?<button onClick={()=>change(x.id,'published','đã công bố')} className="h-fit px-3 py-2 bg-slate-800 text-white text-sm rounded-lg"><Send size={14} className="inline"/> Công bố</button>:null}</div></article>)}</div></div> }
function Content({items,setItems,log}:{items:string[];setItems:React.Dispatch<React.SetStateAction<string[]>>;log:(s:string)=>void}) {const [value,setValue]=useState('');const add=()=>{if(value.trim()){setItems(x=>[...x,value.trim()]);log(`đã tạo nội dung “${value.trim()}”.`);setValue('')}};return <div><h2 className="text-2xl font-bold">Quản lý nội dung</h2><p className="text-slate-500 mt-1 mb-6">Cập nhật gian hàng, bài viết và bản đồ không cần sửa mã nguồn.</p><section className="bg-white border rounded-xl p-5"><div className="flex gap-2 mb-5"><input className="input-field" value={value} onChange={e=>setValue(e.target.value)} placeholder="Tên gian hàng hoặc bài viết mới"/><button onClick={add} className="px-4 bg-emerald-600 text-white rounded-lg"><Plus/></button></div>{items.map((x,i)=><div className="py-4 border-t flex justify-between" key={x}><span className="flex gap-3"><Store size={18} className="text-emerald-600"/>{x}</span><button onClick={()=>{setItems(a=>a.filter((_,n)=>n!==i));log(`đã xóa nội dung “${x}”.`)}} className="text-sm text-red-600">Xóa</button></div>)}</section></div> }
function Audit({logs}:{logs:string[]}) {return <div><h2 className="text-2xl font-bold">Nhật ký hoạt động</h2><p className="text-slate-500 mt-1 mb-6">Lưu vết thay đổi quan trọng trong cổng quản trị.</p><section className="bg-white border rounded-xl">{logs.map((x,i)=><div className="p-5 border-b last:border-0 flex gap-3" key={`${x}${i}`}><i className="w-2 h-2 rounded-full bg-emerald-500 mt-1.5 shrink-0"/><p className="text-sm">{x}</p></div>)}</section></div> }
